site_name: Python Microservices Sample App
site_description: Python Microservices Sample App

nav:
  - Overview: index.md
  - Adding AI to Your Services: ai-integration.md
  - Security Demo (Instructor): devastator.md

plugins:
  - techdocs-core
